### ISSUE TITLE
Add me as a contributor

### ISSUE THREAD

**Issue by neuhausr** [maptime/map-accessibility-guidelines#12]
I think I have some things I could add. Let me know if you'd rather have me run things by you first, though.

**Comment by MitchSchaps** [comment]
Added

**Comment by geospatialem** [comment]
Thanks for the request, @neuhausr and @MitchSchaps for making it happen so fast! Looking forward to the additions you've got, Brad! And definitely a great idea to add Brad as a contributor. 

This is a reminder to the @maptime/admin-accessibility organizers that we should ask those looking to contribute to send us PR's, and if they submit many PR's, we can give them contributor access. But in many cases, if users only need to submit one or two PR's, we shouldn't need to give them full write access.

**Comment by neuhausr** [comment]
Thanks! 

One process question: most of the pages on here are wiki pages, and they seem to not have the same PR workflow. That is, I did a fork of the site, but when I went to the wiki page on the fork, it is blank. I suppose it'd be possible to copy & paste from the master wiki to the fork wiki, but that seems hacky. I'm pretty new to github--is there something I'm missing?

**Comment by geospatialem** [comment]
Thanks for the great questions!

We've got the Wiki site open so you can **edit the Wiki pages directly on the main repo site** (anyone with a GitHub account can currently do so). We may/may not close this depending on what happens moving forward, but contributors _should always_ have write access.

Also, since you've been added as a contributor to the project, you can **edit directly to the repo** (no need for forking the repo). Hope that helps! :smile: 

Let us know if any other questions come up!
