### ISSUE TITLE
Map legend expanded by default

### ISSUE THREAD

**Issue by Malvoz** [maptime/map-accessibility-guidelines#18]
Having the [Map legend expanded by default](https://github.com/maptime/map-accessibility-guidelines/blob/master/code-snippets/map-legend.md) means that keyboard-only users have to tab through each item as opposed to having the option to skip the content within the component. The advice I think is contradictory to the WCAG 2.1 technique [Using an expandable and collapsible menu to bypass block of content](https://www.w3.org/WAI/WCAG21/Techniques/client-side-script/SCR28.html) (the technique satisfies Success Criterion 2.4.1: Bypass Blocks).

Highlighting some relevant information from [Understanding Success Criterion 2.4.1: Bypass Blocks](https://www.w3.org/WAI/WCAG21/Understanding/bypass-blocks):

> This is in contrast to a sighted user's ability to ignore the repeated material either by focusing on the center of the screen (where main content usually appears) or a mouse user's ability to select a link with a single mouse click rather than encountering every link or form control that comes before the item they want.

> Benefits
> When this Success Criterion is not satisfied, it may be difficult for people with some disabilities to reach the main content of a Web page quickly and easily:
> 
> - People who use only the keyboard or a keyboard interface can reach content with fewer keystrokes. Otherwise, they might have to make dozens of keystrokes before reaching a link in the main content area. This can take a long time and may cause severe physical pain for some users.

**Comment by geospatialem** [comment]
Hi @Malvoz, that's a good point for legends that users have to tab through.

However not always necessarily the case, since some legends can be images with alt text, or could potentially by bypassed by the keyboard entirely (since this would supplement visual users, it could potentially be okay to bypass for screen reader users).

Maybe we can reword the recommendation to fit this? Would you be willing to reword the section in a Pull Request?
